package com.algonquin.final_mobil_dev;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

// #8.5 ImageEntity
/**
 * Represents an image entity in the database.
 * This class is annotated as an Entity for Room to create a table named "images".
 */
@Entity(tableName = "images")
public class ImageEntity {
    /**
     * The primary key for the image entity.
     * It is auto-generated by the database.
     */
    @PrimaryKey(autoGenerate = true)
    public int id;

    /**
     * The name of the image.
     */
    public String name;

    /**
     * The URL of the image.
     */
    public String url;

    /**
     * The date associated with the image.
     */
    public String date;
}